channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.2.4
- pip:
  - mlflow==2.9.0
  - cloudpickle==2.0.0
  - numpy==1.23.5
  - packaging==23.2
  - psutil==5.8.0
  - pyyaml==6.0.1
  - scikit-learn==0.24.2
  - scipy==1.9.0
  - typing-extensions==4.9.0
name: mlflow-env
